server:
  port: ${PORT:8081}

spring:
  application:
    name: notification-service
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:test-project}
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:}

pubsub:
  subscription: notification-sub

management:
  endpoints:
    web:
      exposure:
        include: health,info
