apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-service-deployment
  labels:
    app: bar-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: ["us-central1-a", "us-central1-c"]
      containers:
      - name: bar-service
        image: docker.io/nagabhushanamn/bar-service:v3
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        volumeMounts:
        - name: bar-service-storage
          mountPath: /data
      volumes:
      - name: bar-service-storage
        persistentVolumeClaim:
          claimName: bar-service-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bar-service-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bar-service-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data