
OCI specification defines a standard format for container images and runtimes. Dockerfile is a text file that contains instructions to build a Docker image. Below are some common Dockerfile instructions:

- ARG <variable>=<default-value>
- FROM <base-image>
- LABEL maintainer="<maintainer-email>"
- MAINTAINER <maintainer-name>
- WORKDIR ${variable}
- RUN <command-to-install-dependencies>
- COPY . /app
- ADD <source> <destination>
- ENV <key>=<value>
- EXPOSE <port>
- USER <user>
- STOPSIGNAL <signal>
- VOLUME <path>
- SHELL ["<shell>", "<option>"]
- HEALTHCHECK --interval=<interval> --timeout=<timeout> --start-period=<start-period> --retries=<retries> CMD <command>
- ONBUILD <instruction>
- ENTRYPOINT ["<executable>", "<param1>", "<param2>"]
- CMD ["<command>", "<param1>", "<param2>"]

------------

docker build -t <image-name>:<tag> .
docker run -d -p <host-port>:<container-port> <image-name>:<tag>
docker run -d -p <host-port>:<container-port> <image-name>:<tag> cmd2