server:
  port: ${PORT:8083}
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: analytics-service-bigquery
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:test-project}

# Pub/Sub subscription
pubsub:
  subscription: ${PUBSUB_SUBSCRIPTION:analytics-sub}

# BigQuery config
bigquery:
  dataset: ${BQ_DATASET:upi_analytics}
  table: ${BQ_TABLE:transactions}

management:
  endpoints:
    web:
      exposure:
        include: health,info
