server:
  port: ${PORT:8083}

spring:
  application:
    name: analytics-service
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:test-project}
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:}

pubsub:
  subscription: analytics-sub

management:
  endpoints:
    web:
      exposure:
        include: health,info
